
pluginManagement {
	repositories {
		maven {
			// RetroFuturaGradle
			name "GTNH Maven"
			url "https://nexus.gtnewhorizons.com/repository/public/"
			mavenContent {
				includeGroup("com.gtnewhorizons")
				includeGroupByRegex("com\\.gtnewhorizons\\..+")
			}
		}
		maven {
			name "JitPack"
			url "https://jitpack.io"
			mavenContent {
				includeGroupByRegex("com\\.github\\..+")
			}
		}
		gradlePluginPortal()
		mavenCentral()
		mavenLocal()
	}
}

plugins {
	id 'com.gtnewhorizons.gtnhsettingsconvention' version '1.0.38'
}

// include("depTools")
